version: '3.9'

services:
  mysql:
    image: mysql:8
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=23
      - MYSQL_PASSWORD=23
      - MYSQL_USER=mj
      - MYSQL_DATABASE=nba
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
  dbbuilder:
   build: ./dbbuilder
   depends_on:
       mysql:
           condition: service_healthy
  webapp:
   build: ./webapp
   ports:
     - "5000:5000"
   depends_on:
       mysql:
           condition: service_healthy